# Generated by Django 4.1.7 on 2023-03-22 06:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latestpg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_image', models.ImageField(upload_to='latestpg/latestpg_image/', verbose_name='Pg Image')),
                ('pg_location', models.CharField(max_length=255)),
                ('pg_rent', models.FloatField()),
                ('pg_name', models.CharField(max_length=255)),
                ('pgtype', models.CharField(choices=[('for girls&boys', 'for girls&boys'), ('All prepared', 'All prepared')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PgFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.CharField(max_length=200)),
                ('washroom', models.CharField(max_length=200)),
                ('Balcony', models.CharField(max_length=200)),
                ('cupboard', models.CharField(max_length=200)),
                ('tv', models.CharField(max_length=200)),
                ('dth', models.CharField(max_length=200)),
                ('wifi', models.CharField(max_length=200)),
                ('side_table', models.CharField(max_length=200)),
                ('mattress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='property/feature_image/', verbose_name='Feature Image')),
                ('location', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('li_title1', ckeditor.fields.RichTextField()),
                ('no_of_bedroom', models.IntegerField(blank=True, null=True, verbose_name='Number of Bedroom')),
                ('li_title2', ckeditor.fields.RichTextField()),
                ('no_of_bathroom', models.IntegerField(blank=True, null=True, verbose_name='Number of Bathroom')),
                ('li_title3', ckeditor.fields.RichTextField()),
                ('no_of_kitchen', models.IntegerField(blank=True, null=True, verbose_name='Number of Kitchen')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='property/author_image/', verbose_name='Author Image')),
                ('author_name', models.CharField(blank=True, max_length=233, null=True, verbose_name='Author Name')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('cartegory', models.ManyToManyField(related_name='property_category', to='properties_engine.category')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties_engine.propertytype')),
            ],
        ),
        migrations.DeleteModel(
            name='Properity',
        ),
    ]
