# Generated by Django 4.1.7 on 2023-03-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0002_latesflat_latestpg_pgfacility_pgtype_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('sale_image', models.ImageField(upload_to='propertysale/sale_image', verbose_name='Sale Image')),
                ('sale_price', models.FloatField()),
                ('sale_address', models.CharField(max_length=200)),
                ('sale_area', models.IntegerField()),
            ],
        ),
    ]
