# Generated by Django 4.1.7 on 2023-03-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0002_latestpg_pgfacility_property_delete_properity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestpg',
            name='key_facilities',
        ),
    ]
