# Generated by Django 4.1.7 on 2023-03-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0003_remove_latestpg_key_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestpg',
            old_name='girls_boys',
            new_name='pgtype',
        ),
    ]
