# Generated by Django 4.1.7 on 2023-03-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0002_latestpg_pgfacility_property_delete_properity'),
        ('properties_engine', '0003_propertyforsale'),
    ]

    operations = [
    ]
