# Generated by Django 4.1.7 on 2023-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0004_rename_girls_boys_latestpg_pgtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='latestpg',
            name='pg_facility',
            field=models.ManyToManyField(related_name='pgfacility', to='properties_engine.pgfacility'),
        ),
        migrations.RemoveField(
            model_name='latestpg',
            name='pgtype',
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='Balcony',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='ac',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='cupboard',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='dth',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='mattress',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='side_table',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='tv',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='washroom',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pgfacility',
            name='wifi',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='latestpg',
            name='pgtype',
            field=models.ManyToManyField(related_name='pg_type', to='properties_engine.pgtype'),
        ),
    ]
