# Generated by Django 4.1.7 on 2023-03-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0006_rename_balcony_pgfacility_facility_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestpg',
            name='pg_facility',
        ),
        migrations.AddField(
            model_name='latestpg',
            name='ac',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='balcony',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='cupboard',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='dth',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='matress',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='side_table',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='washroom',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestpg',
            name='wifi',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
