# Generated by Django 4.1.7 on 2023-03-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0009_latesflat_area_latesflat_flat_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latesflat',
            old_name='location',
            new_name='flat_location',
        ),
    ]
