# Generated by Django 4.1.7 on 2023-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_engine', '0010_rename_location_latesflat_flat_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
